### ISSUE TITLE
Using normal sleep rules (SpongeForge)

### ISSUE THREAD

**Issue by cobaltw** [CosmicDan-Minecraft/SleepingOverhaul#14]
I'm hosting a server that uses SpongeForge, and while using this mod, beds function as they normally do in vanilla. The time does speed up while in bed, but after a moment it will set the time to day and kick the player out of bed.
Disabling SpongeForge results in the mod functioning as expected. Nothing of note appears in the log file or server console.

SpongeForge version 1.12.2-2838-7.4.7
Forge version 14.23.5.2860
Latest versions of SleepingOverhaul, Tickrate Changer, and CosmicLib

**Comment by cosmicdan** [comment]
SpongeForge is not supported. Furthermore, mod is EOL. Others are free to fork it and update it.
