### ISSUE TITLE
Comforts and Sleeping Overhaul conflict

### ISSUE THREAD

**Issue by PurpleHel** [CosmicDan-Minecraft/SleepingOverhaul#2]
With sleeping overhaul installed, sleeping bags from comforts don't work. (I didn't try hammocks.) I dunno which mod is causing the problem. Have a log! https://pastebin.com/WxJM2WD9

https://github.com/TheIllusiveC4/Comforts/issues/17

**Comment by cosmicdan** [comment]
Yeah, I'll have to inspect this mod and try and add special handling. Right now my mod expects bed blocks to be based on the vanilla bed, but I'm guessing the Sleeping Bag is not.

Thanks!

**Comment by cosmicdan** [comment]
Closing this for now as the Comforts mod makes forceful and destructive core class changes which is not only strongly against the Forge etiquette and rules set by Lex, but also breaks the CMC in SleepingOverhaul. Sorry!

Feel free to re-report if/when the Comforts rewrite happens and if it still has a problem.

**Comment by cosmicdan** [comment]
I've fixed it internally to not crash, but note that this is only for the "item-use" mode of Sleeping Bag. The Sleeping Bag will behave like a vanilla bed in this mode (skips to day).

If your sneak-use the sleeping bag and place it on the ground first, then Sleeping Overhaul will work already in the current version.

**Comment by PurpleHel** [comment]
Cool, I'll add sleeping overhaul back then, since there's a workaround! And it wasn't causing a crash, just making Comforts sleeping bags not work. Sorry/You're welcome to have found a mod incompatibility. :)
