### ISSUE TITLE
Crash when trying to load with CMC

### ISSUE THREAD

**Issue by corgiblu** [CosmicDan-Minecraft/SleepingOverhaul#3]
https://paste.dimdev.org/ruwoxiriva.sql

sorry for lazy isssue sudden change of plans and i have to leave my house soon

forge version : 14.23.5.2768

**Comment by cosmicdan** [comment]
You tried to load with "Dev" version, but that's for other modders to use in their development. You need the non-Dev version :)

**Comment by corgiblu** [comment]
Ooh that makes sense! Thanks!

**Comment by corgiblu** [comment]
Could you point me to the download of CMC? I can't seem to find it.

**Comment by cosmicdan** [comment]
It's under "Additional Files" on the Download page, same place you accidently got the deobf jar from.

**Comment by cosmicdan** [comment]
Wait - re-opening this. You have the CMC already, there is only one version. And you have the main mod already? NOT the "deobf" version?

Yeah, that seems all fine - apologies, my reply was rushed too.

I actually have no idea why this is happening. For some reason the CoreMod thinks your instance is a MCP/Forge dev one, but nobody else is getting this issue... 

You sure you meet the Requirements as listed in the Changelog?

**Comment by corgiblu** [comment]
I'll take a look when I get back home. Out shopping right now.

**Comment by corgiblu** [comment]
I know I have the main mod, installed it through twitch so unless the main
download is wrong. But it works without cmc.

**Comment by cosmicdan** [comment]
Fixed this on my end. Forge added a new Event for checking if sleep is allowed at the current time, and that broke the "Allow sleep during day" part of the coremod. Good news now is that the Allow sleep during day feature is part of the base mod and doesn't need the CMC.

I need to fix Timelapse and Sleep-Vote for Nether dimension which I'm doing right now (at the moment, all that happens is that it allows you to lie in bed in the nether but nothing else happens).

Once that's done, 1.0.0 will be released.
