### ISSUE TITLE
[Request] increase randomtickrate to match tickrate during sleep to simulate crops etc. as well

### ISSUE THREAD

**Issue by xkforce** [CosmicDan-Minecraft/SleepingOverhaul#4]
Currently sleepingoverhaul uses the tickratechanger mod to increase the tickrate during sleep to simulate the passage of time.  But the problem is that since crops and other blocks that use randomtickrate instead, these crops grow normally instead of growing at the rate they would be expected to during the amount of time the player is sleeping.

**Comment by cosmicdan** [comment]
Are you absolutely sure about that? I'm almost certain I remember testing Tickrate Changer with trees, and it did indeed seem to increase the rate at which they grow.

On 26 Nov 2018, xkforce <notifications@github.com> wrote:
>Currently sleepingoverhaul uses the tickratechanger mod to increase the
>tickrate during sleep to simulate the passage of time.  But the problem
>is that since crops and other blocks that use randomtickrate instead,
>these crops grow normally instead of growing at the rate they would be
>expected to during the amount of time the player is sleeping.

-- 
Sent with <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> - the evolution of emailing.

**Comment by xkforce** [comment]
https://www.twitch.tv/videos/340885745

There's a test I ran a few minutes ago.

I also tried this with cacti both with the bed and with the randomTickSpeed gamerule.  The difference in growth rate between the tick rate set in the config and the equivalent randomtickspeed gamerule setting (3 is the default for randomtickspeed and 20 for the tickrate so the equivalent for 1000 tickrate is 150 randomtickspeed since 1000 * 3/20 = 150) is noticeable.

https://github.com/Guichaguri/TickrateChanger/issues/6

There's the issue report I made about it on tickratechanger to make sure it wasn't something on their end.

**Comment by cosmicdan** [comment]
Dont crops need a light source to grow? I didn't see you put a torch down.

**Comment by xkforce** [comment]
Yes crops need light and these crops are out in the open sun.  I've done many other tests, this was just a very short example.  The growth rate of crops with tickratechanger are about 5x faster than they normally are but that is about 10x slower than they should be.  About 90% of plant growth appears to be the result of randomtickrate rather than scheduled ticks.

**Comment by cosmicdan** [comment]
Well I'm afraid this is outside the scope of Sleeping Overhaul. It's something that should be done on Tickrate Changer's end, if he has the time or interest to do so.
