### ISSUE TITLE
[suggestion] config option to turn off announcement of current time

### ISSUE THREAD

**Issue by xkforce** [CosmicDan-Minecraft/SleepingOverhaul#5]
Ideally I'd like to be able to turn off the time notification because I think it would fit into the pack better that way but there doesn't appear to be a config option that allows this.

**Comment by cosmicdan** [comment]
You mean the on-screen time display while laying in bed? Sure, already done it on my end - will be there in 1.0. Just need to finish up one more thing before the release is ready.

**Comment by xkforce** [comment]
thank you
