### ISSUE TITLE
Skipping to daytime in single player

### ISSUE THREAD

**Issue by en3on** [CosmicDan-Minecraft/SleepingOverhaul#6]
I'm playing on 1.12.2, and whenever I go to sleep, the clock shows up, but the tick rate does not increase and a few seconds later the screen fades and then skips to day.

**Comment by cosmicdan** [comment]
Must be a mod incompatibility. More and more mods are enchancing sleep themselves which conflicts. Please check all your mods and their configs for sleep changes and try to find the conflict. Also check the Curse page for compatibility notes.

On 1 Feb 2019, en3on <notifications@github.com> wrote:
>I'm playing on 1.12.2, and whenever I go to sleep, the clock shows up,
>but the tick rate does not increase and a few seconds later the screen
>fades and then skips to day.

-- 
Sent with <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> - the evolution of emailing.

**Comment by en3on** [comment]
Alright. Time to go through my 150 mods haha!

Thanks for your help :)

**Comment by cosmicdan** [comment]
Sadly that's often required to fix mod incompatibilities (or start to) :)

Pro-Tip - Remove only half the mods. If the problem still occurs, you know it's in the remaining half so remove another half of those and repeat. If the problem is gone, add back half of the mods you removed - and continue like that. Make sense? Optimal process of elimination.

**Comment by en3on** [comment]
Nice tip!

Cheers!

**Comment by cosmicdan** [comment]
Oh - might be a good idea to confirm that the mod is actually still working even without any other mods at all (except Tickrate Changer and CosmicLib obviously as they're required). You didn't mention what Forge version you're on but it's always possible that Forge has made changes which broke the Timelapse hooks.
