### ISSUE TITLE
[ISSUE] SleepingOverhaul mod with length of day time Increased

### ISSUE THREAD

**Issue by Xelbayria** [CosmicDan-Minecraft/SleepingOverhaul#8]
Hello, 

I am using a mod called Primal Core where it has a feature that allow me to increase the length of the day from 20 minutes to 24 minutes. Of course, we know there are some mods that has this features. So when I sleep with the time that goes from 11pm to 8am and it's time to wake up... 

The issue is that the time is not matching with the time of the day because it become longer than 20 minutes.  I would suggest that you try make Sleep Overhaul depends on the rate of the system rather than the constant ticking rate OR Sleeping Overhaul's own system of constant rate. 

that way, the rate of the system will changing if I changed the time of the day to 30 minutes... But constant rate doesn't change because it wasn't affected.

**Comment by cosmicdan** [comment]
Primal Core is a problematic mod that often doesn't play nice with others, I've found. It's also closed source so it's painful to deal with.

I recommend using B3M to change day length instead. It's far more compatible with other mods.

⁣Get BlueMail for Android ​

**Comment by Xelbayria** [comment]
alright, got it. thanks for telling me. I guess there is nothing we can do about it. I'll close this issue.
